--
-- Файл сгенерирован с помощью SQLiteStudio v3.4.17 в Чт дек 4 01:56:03 2025
--
-- Использованная кодировка текста: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Таблица: Stations
CREATE TABLE IF NOT EXISTS Stations (id NUMERIC PRIMARY KEY, st_name TEXT, region TEXT);
INSERT INTO Stations (id, st_name, region) VALUES (1, 'Решоты-Северные', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (2, 'Прохладная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (3, 'Канифольная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (4, 'Табагашет', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (5, 'Южная Тунгуска', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (6, 'Поканаевка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (7, '58 км', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (8, 'Тиличет', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (9, 'Плашечная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (10, 'Черманчет', 'Иркутская область');
INSERT INTO Stations (id, st_name, region) VALUES (11, 'Шелаево', 'Иркутская область');
INSERT INTO Stations (id, st_name, region) VALUES (12, 'Новобирюсинская', 'Иркутская область');
INSERT INTO Stations (id, st_name, region) VALUES (13, 'Гаревой', 'Иркутская область');
INSERT INTO Stations (id, st_name, region) VALUES (14, 'Тамтачет', 'Иркутская область');
INSERT INTO Stations (id, st_name, region) VALUES (15, 'Чунояр', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (16, 'Лапшиха', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (17, 'Тулат', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (18, 'Изык-Чуль', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (19, 'Таёжная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (20, 'Беловка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (21, 'Кытат', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (22, 'Кипрейный', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (23, 'Улановая', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (24, 'Суриково', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (25, 'Ганина Гарь', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (26, 'Малая Кеть', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (27, 'Чайда', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (28, 'Комаровка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (29, 'Большая Кеть', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (30, 'Икшурма', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (31, 'Пировская', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (32, 'Бельский', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (33, 'Кемский', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (34, 'Абалаково', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (35, 'Лесосибирск-1', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (36, 'Шушь', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (37, 'Дубинино', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (38, 'Инголь', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (39, 'Полуторник', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (40, 'Саланга', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (41, 'Кия-Шалтырь', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (42, 'Бельтыры', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (43, 'Ворошилово', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (44, 'Усть-Есь', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (45, 'Усть-Тыштып', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (46, 'Таштып', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (47, 'Сартак', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (48, 'Хараджуль', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (49, 'Сартабан', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (50, 'Абаза', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (51, 'Саяногорск', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (52, 'Предзаводская', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (100, 'Междуреченск-Пасс.', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (101, 'Деповская', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (102, 'Городская', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (103, 'Карай', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (104, 'Садовая', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (105, '75 км', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (106, 'Озерки', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (107, '80 км', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (108, 'Чульжан', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (109, 'Геологическая', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (110, 'Студёный Плес', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (111, 'Бельсу', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (112, 'Лосиный Камень', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (113, 'Борсики', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (114, 'Теба', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (115, 'Пороги', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (116, 'Сливень', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (117, 'Борисовка', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (118, 'Лужба', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (119, 'Топчул', 'Кемеровская область');
INSERT INTO Stations (id, st_name, region) VALUES (120, 'Турбаза "Восход"', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (121, 'Калтас', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (122, 'Чарыш', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (123, 'Балыксу', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (124, 'Шора', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (125, 'Казынет', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (126, 'Бискамжа', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (127, 'Ясная Полянка', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (128, 'Алатау', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (129, 'Западный Портал', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (130, 'Нанхчул', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (131, 'Хабзас', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (132, 'Дачи', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (133, 'Биркчул', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (134, 'Югачи', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (135, 'Историческая', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (136, 'Казановская', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (137, 'Верхний Аскиз', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (138, 'Кизлас', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (139, 'Аскиз', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (140, 'Локомотивное Депо', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (141, 'Раздольная', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (142, 'Чартыковский', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (143, 'Камышта', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (144, 'Скальная', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (145, 'Уйтак', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (146, 'Ханкуль', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (147, 'Кирба', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (148, 'База МК', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (149, 'Дачная', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (150, 'Хоных', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (151, 'Тигей', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (152, 'Красное Озеро', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (153, 'Урожайная', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (154, 'Районная Подстанция', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (155, 'Ташеба', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (156, 'Путейский Городок', 'Республика Хакассия');
INSERT INTO Stations (id, st_name, region) VALUES (157, 'Садовая', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (158, 'Минусинск', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (159, 'Тагарский', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (160, 'Крупская', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (161, 'Каныгино', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (162, 'Казылкульский', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (163, 'Пионерская', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (164, 'Жерлык', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (165, 'Шошино', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (166, 'Туба', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (167, 'Мальцево', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (168, 'Роща', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (169, 'Заречная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (170, 'Курагино', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (171, 'Берёзовая', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (172, 'Ирба', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (173, 'Красный Кордон', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (174, 'Тоннельная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (175, 'Кизир', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (176, 'Ягодное', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (177, 'Журавлёво', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (178, 'Усть-Каспа', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (179, 'Каспа', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (180, '557 км', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (181, 'Кошурниково', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (182, 'Боготол', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (183, 'Заводская', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (184, 'Шулдат', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (185, 'Вагино', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (186, 'Куйбышево', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (187, 'Журавлиха', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (188, 'Критово', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (189, 'Красная Речка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (190, 'Степановка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (191, 'Клубничная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (192, 'Зерцалы', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (193, 'База ПМС', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (194, 'Белый Яр', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (195, 'Нагорново', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (196, 'Подсобное Хозяйство', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (197, 'Чулым', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (198, 'Ачинск-1', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (199, 'Транспортная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (200, 'Салырка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (201, 'Иринка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (202, 'Грибная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (203, 'Козловка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (204, 'Покровка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (205, 'Тарутино', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (206, 'Боровка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (207, '3944 км', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (208, 'Ибрюль', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (209, 'Юбилейная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (210, 'Железнодорожный Посёлок', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (211, 'Чернореченская', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (212, 'Карпицкая', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (213, 'Постойка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (214, 'Весёлая', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (215, 'Шушковский', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (216, 'Малиногорка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (217, 'Каменка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (218, 'Козулька', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (219, 'Черёмушки', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (220, 'Шарловский', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (221, 'Листвянка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (222, 'Косачи', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (223, 'Боровой', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (224, 'Кемчуг', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (225, 'Сергино', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (226, 'Горная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (227, 'Бадаложный', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (228, 'Зеледеево', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (229, 'Водораздел', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (230, 'Крючково', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (231, 'Лесная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (232, 'Известковая', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (233, 'Кача', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (234, 'Щебёночный Завод', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (235, 'Тростенцево', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (236, '4056 км', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (237, 'Еловка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (238, 'Снежница', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (239, 'Рябинино', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (240, 'Караульная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (241, 'Минино', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (242, 'Пугачёво', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (243, 'Колягино', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (244, 'Овинный', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (245, 'Базаиха', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (246, '4119 км', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (247, 'Сады', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (248, '4122 км', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (249, '4123 км', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (250, 'Сухой', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (251, '4127 км', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (252, 'Зыково', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (253, 'Восток', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (254, 'Петряшино', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (255, 'Родники', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (256, 'Маганская', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (257, 'Березовка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (258, 'Шушун', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (259, 'Луговая', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (260, 'Камас', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (261, 'Сорокино', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (262, 'Самарка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (263, 'Правая', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (264, 'Таёжный', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (265, 'Заречье', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (266, 'Пономарёво', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (267, 'Юбилейный', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (268, 'Камарчага', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (269, 'Есауловка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (270, 'Пинчино', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (271, 'Тингинский', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (272, 'Балай', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (273, 'Карабарик', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (274, 'Косогор', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (275, 'Марьевка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (276, 'Озерный', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (277, 'Наливная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (278, 'Путейская', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (279, 'Уяр', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (280, 'Преображенская', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (281, 'Громадская', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (282, 'Сибиряк', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (283, 'Илиган', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (284, 'Налобино', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (285, 'Заозёрная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (286, 'Ирша', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (287, 'Южная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (288, 'Камала', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (289, 'Камалинка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (290, 'Солнечная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (291, 'Ягодная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (292, 'Солянка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (293, 'Старая Солянка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (294, 'Перевал', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (295, 'Бошняково', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (296, 'Безводная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (297, 'Комаровская', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (298, 'Филимоново', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (299, 'Ферма', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (300, 'Красный Маяк', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (301, 'Аэродром', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (302, 'Канск-Енисейский', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (303, 'Канск-Перевоз', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (304, 'Иланка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (305, 'Старая Иланка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (306, 'Коньково', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (307, 'Лозичная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (308, 'Далай', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (309, 'Тёплые Ключи', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (310, 'Луговые', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (311, 'Иланская', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (312, 'Бузюк', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (313, 'Дачная', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (314, 'Стайный', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (315, 'Сулемка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (316, 'Верхний Ингаш', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (317, 'Ингашская', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (318, 'Куруп', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (319, '4409 км', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (320, 'Пойма', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (321, 'Шарбыш', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (322, 'Максимово', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (323, 'Тинская', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (324, 'Прибылово', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (325, 'Догадаево', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (326, '4443 км', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (327, 'Сосновый Бор', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (328, 'Решоты-Южные', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (329, 'Красная Сопка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (330, 'Глядень', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (331, 'Сереж', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (332, 'Назарово', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (333, 'Чулымка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (334, 'Улуй', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (335, 'Пригородный', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (336, 'Ачинск-2', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (337, 'Тимонино', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (338, 'Новопятницкий', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (339, 'Татьяновка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (340, 'Авда', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (341, 'Переяславка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (342, 'Снегирёвка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (343, 'Саянская', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (344, 'Калиновка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (345, 'Стойба', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (346, 'Илей', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (347, 'Кравченко', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (348, '733 км', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (349, 'Лукашевич', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (350, 'Кой', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (351, 'Отроги', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (352, 'Мана', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (500, 'Северное Шоссе', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (501, 'Водопьянова', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (502, 'Красноярск-Северный', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (503, 'Тихие Зори', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (504, 'Бобровый Лог', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (505, 'Красноярские Столбы', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (506, 'Турбаза', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (507, 'Слизнево', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (508, 'Овсянка', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (509, 'Молодёжный', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (510, 'Усть-Мана', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (511, 'Нижняя Мана', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (512, 'Дивногорск', 'Красноярский край');
INSERT INTO Stations (id, st_name, region) VALUES (513, 'Мясокомбинат', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (514, 'Бугач', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (515, 'Калинина', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (516, 'Путепровод', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (517, 'Красноярск-Пасс.', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (518, 'Железнодорожная Больница', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (519, 'Платинум Арена', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (520, 'Енисей', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (521, 'Белые Росы', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (522, 'Студенческая', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (523, 'Первомайская', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (524, 'Злобино', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (525, 'Октябрьская', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (526, 'Шинный Завод', 'Красноярск');
INSERT INTO Stations (id, st_name, region) VALUES (527, 'Питомник', 'Абакан');
INSERT INTO Stations (id, st_name, region) VALUES (528, 'Городок ПМС', 'Абакан');
INSERT INTO Stations (id, st_name, region) VALUES (529, 'Абакан', 'Абакан');
INSERT INTO Stations (id, st_name, region) VALUES (530, 'Мостоотряд', 'Абакан');
INSERT INTO Stations (id, st_name, region) VALUES (531, 'Подсиний', 'Абакан');
INSERT INTO Stations (id, st_name, region) VALUES (532, 'Енисейская', 'Абакан');
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);
INSERT INTO Stations (id, st_name, region) VALUES (NULL, NULL, NULL);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
